<?php
/**
 * AlternateRatesResponseFreightDensityRateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\TForceFreightRating
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freight Rate
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\TForceFreightRating;

use PHPUnit\Framework\TestCase;

/**
 * AlternateRatesResponseFreightDensityRateTest Class Doc Comment
 *
 * @category    Class
 * @description FreightDensityRate container.
 * @package     UPS\TForceFreightRating
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AlternateRatesResponseFreightDensityRateTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AlternateRatesResponseFreightDensityRate"
     */
    public function testAlternateRatesResponseFreightDensityRate()
    {
    }

    /**
     * Test attribute "density"
     */
    public function testPropertyDensity()
    {
    }

    /**
     * Test attribute "total_cubic_feet"
     */
    public function testPropertyTotalCubicFeet()
    {
    }
}
