<?php
/**
 * FreightPickupRequestPickupRequestConfirmationNumberTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\FreightPickup
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freight Pickup
 *
 * API can be only used by users that plan to ship packages manifested, tendered, and delivered by TForce Freight
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.45
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\FreightPickup;

use PHPUnit\Framework\TestCase;

/**
 * FreightPickupRequestPickupRequestConfirmationNumberTest Class Doc Comment
 *
 * @category    Class
 * @description Confirmation number of pickup ground freight shipment to modify.� Only use if requesting a pickup modification. If this element is populated, it must contain a valid confirmation number and all previously supplied populated elements in the original request must be present.
 * @package     UPS\FreightPickup
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FreightPickupRequestPickupRequestConfirmationNumberTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FreightPickupRequestPickupRequestConfirmationNumber"
     */
    public function testFreightPickupRequestPickupRequestConfirmationNumber()
    {
    }
}
