<?php
/**
 * TransportationPickUpSchedulePickUpTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\Locator
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Locator
 *
 * The Locator API provides UPS full-service and self-service locations, hours of operation and pickup times.
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.45
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\Locator;

use PHPUnit\Framework\TestCase;

/**
 * TransportationPickUpSchedulePickUpTest Class Doc Comment
 *
 * @category    Class
 * @description Container to hold information regarding pickup day of the week and details.
 * @package     UPS\Locator
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TransportationPickUpSchedulePickUpTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TransportationPickUpSchedulePickUp"
     */
    public function testTransportationPickUpSchedulePickUp()
    {
    }

    /**
     * Test attribute "day_of_week"
     */
    public function testPropertyDayOfWeek()
    {
    }

    /**
     * Test attribute "pick_up_details"
     */
    public function testPropertyPickUpDetails()
    {
    }
}
