<?php
/**
 * FreightPickupRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\TForceFreightPickup
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freight Pickup
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\TForceFreightPickup;

use PHPUnit\Framework\TestCase;

/**
 * FreightPickupRequestTest Class Doc Comment
 *
 * @category    Class
 * @description FreightPickupRequest
 * @package     UPS\TForceFreightPickup
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FreightPickupRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FreightPickupRequest"
     */
    public function testFreightPickupRequest()
    {
    }

    /**
     * Test attribute "request"
     */
    public function testPropertyRequest()
    {
    }

    /**
     * Test attribute "pickup_request_confirmation_number"
     */
    public function testPropertyPickupRequestConfirmationNumber()
    {
    }

    /**
     * Test attribute "destination_postal_code"
     */
    public function testPropertyDestinationPostalCode()
    {
    }

    /**
     * Test attribute "destination_country_code"
     */
    public function testPropertyDestinationCountryCode()
    {
    }

    /**
     * Test attribute "requester"
     */
    public function testPropertyRequester()
    {
    }

    /**
     * Test attribute "ship_from"
     */
    public function testPropertyShipFrom()
    {
    }

    /**
     * Test attribute "ship_to"
     */
    public function testPropertyShipTo()
    {
    }

    /**
     * Test attribute "pickup_date"
     */
    public function testPropertyPickupDate()
    {
    }

    /**
     * Test attribute "earliest_time_ready"
     */
    public function testPropertyEarliestTimeReady()
    {
    }

    /**
     * Test attribute "latest_time_ready"
     */
    public function testPropertyLatestTimeReady()
    {
    }

    /**
     * Test attribute "shipment_service_options"
     */
    public function testPropertyShipmentServiceOptions()
    {
    }

    /**
     * Test attribute "shipment_detail"
     */
    public function testPropertyShipmentDetail()
    {
    }

    /**
     * Test attribute "existing_shipment_id"
     */
    public function testPropertyExistingShipmentId()
    {
    }

    /**
     * Test attribute "pom"
     */
    public function testPropertyPom()
    {
    }

    /**
     * Test attribute "pickup_instructions"
     */
    public function testPropertyPickupInstructions()
    {
    }

    /**
     * Test attribute "additional_comments"
     */
    public function testPropertyAdditionalComments()
    {
    }

    /**
     * Test attribute "handling_instructions"
     */
    public function testPropertyHandlingInstructions()
    {
    }

    /**
     * Test attribute "special_instructions"
     */
    public function testPropertySpecialInstructions()
    {
    }

    /**
     * Test attribute "delivery_instructions"
     */
    public function testPropertyDeliveryInstructions()
    {
    }
}
