<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  UPS\OAuthAuthCode
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OAuth
 *
 * Retrive OAuth Bearer token on behalf of another user
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.45
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace UPS\OAuthAuthCode;

use UPS\OAuthAuthCode\Configuration;
use UPS\OAuthAuthCode\ApiException;
use UPS\OAuthAuthCode\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  UPS\OAuthAuthCode
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for generateToken
     *
     * .
     *
     */
    public function testGenerateTokenForm()
    {
    }

    /**
     * Test case for refreshToken
     *
     * .
     *
     */
    public function testRefreshTokenForm()
    {
    }

    /**
     * Test case for validateClient
     *
     * .
     *
     */
    public function testValidateClient()
    {
    }
}
