<?php
/**
 * ShipmentServiceOptionsPickupOptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freight Rate
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * ShipmentServiceOptionsPickupOptionsTest Class Doc Comment
 *
 * @category    Class
 * @description PickupOptions Container.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShipmentServiceOptionsPickupOptionsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ShipmentServiceOptionsPickupOptions"
     */
    public function testShipmentServiceOptionsPickupOptions()
    {
    }

    /**
     * Test attribute "holiday_pickup_indicator"
     */
    public function testPropertyHolidayPickupIndicator()
    {
    }

    /**
     * Test attribute "inside_pickup_indicator"
     */
    public function testPropertyInsidePickupIndicator()
    {
    }

    /**
     * Test attribute "residential_pickup_indicator"
     */
    public function testPropertyResidentialPickupIndicator()
    {
    }

    /**
     * Test attribute "weekend_pickup_indicator"
     */
    public function testPropertyWeekendPickupIndicator()
    {
    }

    /**
     * Test attribute "lift_gate_required_indicator"
     */
    public function testPropertyLiftGateRequiredIndicator()
    {
    }

    /**
     * Test attribute "limited_access_pickup_indicator"
     */
    public function testPropertyLimitedAccessPickupIndicator()
    {
    }
}
