<?php
/**
 * UploadRequestRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\PaperlessDocuments
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Paperless Document
 *
 * The Paperless Document API web service allows the users to upload their own customized trade documents for customs clearance to Forms History.
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.45
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\PaperlessDocuments;

use PHPUnit\Framework\TestCase;

/**
 * UploadRequestRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Contains Paperless Document API upload request criteria components.  N/A
 * @package     UPS\PaperlessDocuments
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UploadRequestRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UploadRequestRequest"
     */
    public function testUploadRequestRequest()
    {
    }

    /**
     * Test attribute "request_option"
     */
    public function testPropertyRequestOption()
    {
    }

    /**
     * Test attribute "sub_version"
     */
    public function testPropertySubVersion()
    {
    }

    /**
     * Test attribute "transaction_reference"
     */
    public function testPropertyTransactionReference()
    {
    }
}
