<?php
/**
 * UserCreatedFormUserCreatedFormDocumentTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\PaperlessDocuments
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Paperless Document
 *
 * The Paperless Document API web service allows the users to upload their own customized trade documents for customs clearance to Forms History.
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.45
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\PaperlessDocuments;

use PHPUnit\Framework\TestCase;

/**
 * UserCreatedFormUserCreatedFormDocumentTypeTest Class Doc Comment
 *
 * @category    Class
 * @description The type of documents in UserCreatedForm file.  The allowed document types are 001 - Authorization Form, 002 - Commercial Invoice, 003 - Certificate of Origin, 004 - Export Accompanying Document, 005 - Export License, 006 - Import Permit, 007 - One Time NAFTA, 008 - Other Document, 009 - Power of Attorney, 010 - Packing List, 011 - SED Document, 012 - Shipper&#x27;s Letter of Instruction, 013 - Declaration. The total number of documents allowed per file or per shipment is 13. Each document type needs to be three digits.
 * @package     UPS\PaperlessDocuments
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserCreatedFormUserCreatedFormDocumentTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UserCreatedFormUserCreatedFormDocumentType"
     */
    public function testUserCreatedFormUserCreatedFormDocumentType()
    {
    }
}
