<?php
/**
 * UserCreatedFormUserCreatedFormFileFormatTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\PaperlessDocuments
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Paperless Document
 *
 * The Paperless Document API web service allows the users to upload their own customized trade documents for customs clearance to Forms History.
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.45
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\PaperlessDocuments;

use PHPUnit\Framework\TestCase;

/**
 * UserCreatedFormUserCreatedFormFileFormatTest Class Doc Comment
 *
 * @category    Class
 * @description The UserCreatedForm file format.  The allowed file formats are bmp, doc, gif, jpg, pdf, png, rtf, tif, txt and xls. The only exceptions for having file format of length 4 character are docx and xlsx. All other file formats needs to be of length 3.
 * @package     UPS\PaperlessDocuments
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserCreatedFormUserCreatedFormFileFormatTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UserCreatedFormUserCreatedFormFileFormat"
     */
    public function testUserCreatedFormUserCreatedFormFileFormat()
    {
    }
}
