<?php
/**
 * ValidateSuccessResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\OAuthAuthCode
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OAuth
 *
 * Retrive OAuth Bearer token on behalf of another user
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.45
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\OAuthAuthCode;

use PHPUnit\Framework\TestCase;

/**
 * ValidateSuccessResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ValidateSuccessResponse
 * @package     UPS\OAuthAuthCode
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ValidateSuccessResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ValidateSuccessResponse"
     */
    public function testValidateSuccessResponse()
    {
    }

    /**
     * Test attribute "result"
     */
    public function testPropertyResult()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "lasso_redirect_url"
     */
    public function testPropertyLassoRedirectUrl()
    {
    }
}
