<?php
/**
 * FreightPickupRequestShipmentServiceOptions
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\TForceFreightPickup
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freight Pickup
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace UPS\TForceFreightPickup\TForceFreightPickup;

use \ArrayAccess;
use \UPS\TForceFreightPickup\ObjectSerializer;

/**
 * FreightPickupRequestShipmentServiceOptions Class Doc Comment
 *
 * @category Class
 * @description ShipmentServiceOptions container.
 * @package  UPS\TForceFreightPickup
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FreightPickupRequestShipmentServiceOptions implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'FreightPickupRequest_ShipmentServiceOptions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'freezable_protection_indicator' => 'string',
        'limited_access_pickup_indicator' => 'string',
        'limited_access_delivery_indicator' => 'string',
        'extreme_length_indicator' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'freezable_protection_indicator' => null,
        'limited_access_pickup_indicator' => null,
        'limited_access_delivery_indicator' => null,
        'extreme_length_indicator' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'freezable_protection_indicator' => 'FreezableProtectionIndicator',
        'limited_access_pickup_indicator' => 'LimitedAccessPickupIndicator',
        'limited_access_delivery_indicator' => 'LimitedAccessDeliveryIndicator',
        'extreme_length_indicator' => 'ExtremeLengthIndicator'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'freezable_protection_indicator' => 'setFreezableProtectionIndicator',
        'limited_access_pickup_indicator' => 'setLimitedAccessPickupIndicator',
        'limited_access_delivery_indicator' => 'setLimitedAccessDeliveryIndicator',
        'extreme_length_indicator' => 'setExtremeLengthIndicator'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'freezable_protection_indicator' => 'getFreezableProtectionIndicator',
        'limited_access_pickup_indicator' => 'getLimitedAccessPickupIndicator',
        'limited_access_delivery_indicator' => 'getLimitedAccessDeliveryIndicator',
        'extreme_length_indicator' => 'getExtremeLengthIndicator'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['freezable_protection_indicator'] = isset($data['freezable_protection_indicator']) ? $data['freezable_protection_indicator'] : null;
        $this->container['limited_access_pickup_indicator'] = isset($data['limited_access_pickup_indicator']) ? $data['limited_access_pickup_indicator'] : null;
        $this->container['limited_access_delivery_indicator'] = isset($data['limited_access_delivery_indicator']) ? $data['limited_access_delivery_indicator'] : null;
        $this->container['extreme_length_indicator'] = isset($data['extreme_length_indicator']) ? $data['extreme_length_indicator'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets freezable_protection_indicator
     *
     * @return string
     */
    public function getFreezableProtectionIndicator()
    {
        return $this->container['freezable_protection_indicator'];
    }

    /**
     * Sets freezable_protection_indicator
     *
     * @param string $freezable_protection_indicator FreezableProtectionIndicator Container.
     *
     * @return $this
     */
    public function setFreezableProtectionIndicator($freezable_protection_indicator)
    {
        $this->container['freezable_protection_indicator'] = $freezable_protection_indicator;

        return $this;
    }

    /**
     * Gets limited_access_pickup_indicator
     *
     * @return string
     */
    public function getLimitedAccessPickupIndicator()
    {
        return $this->container['limited_access_pickup_indicator'];
    }

    /**
     * Sets limited_access_pickup_indicator
     *
     * @param string $limited_access_pickup_indicator Indicates there is limited access for pickups.
     *
     * @return $this
     */
    public function setLimitedAccessPickupIndicator($limited_access_pickup_indicator)
    {
        $this->container['limited_access_pickup_indicator'] = $limited_access_pickup_indicator;

        return $this;
    }

    /**
     * Gets limited_access_delivery_indicator
     *
     * @return string
     */
    public function getLimitedAccessDeliveryIndicator()
    {
        return $this->container['limited_access_delivery_indicator'];
    }

    /**
     * Sets limited_access_delivery_indicator
     *
     * @param string $limited_access_delivery_indicator Indicates there is limited access for deliveries.
     *
     * @return $this
     */
    public function setLimitedAccessDeliveryIndicator($limited_access_delivery_indicator)
    {
        $this->container['limited_access_delivery_indicator'] = $limited_access_delivery_indicator;

        return $this;
    }

    /**
     * Gets extreme_length_indicator
     *
     * @return string
     */
    public function getExtremeLengthIndicator()
    {
        return $this->container['extreme_length_indicator'];
    }

    /**
     * Sets extreme_length_indicator
     *
     * @param string $extreme_length_indicator ExtremeLengthIndicator Container (greater than 15ft)
     *
     * @return $this
     */
    public function setExtremeLengthIndicator($extreme_length_indicator)
    {
        $this->container['extreme_length_indicator'] = $extreme_length_indicator;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
