<?php
/**
 * FactorValueTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\FreightShipping
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freight Ship
 *
 * Only users that plan to ship packages manifested, tendered, and delivered by TForce Freight can use the API.
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.45
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\FreightShipping;

use PHPUnit\Framework\TestCase;

/**
 * FactorValueTest Class Doc Comment
 *
 * @category    Class
 * @description Contains value pertaining to rate type code. For e.g. if discount rate is 25% then rate type code will have code type as DISCOUNT_RATE\&quot; and rate factor value will have 25\&quot;
 * @package     UPS\FreightShipping
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FactorValueTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FactorValue"
     */
    public function testFactorValue()
    {
    }
}
