<?php
/**
 * FreightShipResponseShipmentResultsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\FreightShipping
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freight Ship
 *
 * Only users that plan to ship packages manifested, tendered, and delivered by TForce Freight can use the API.
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.45
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\FreightShipping;

use PHPUnit\Framework\TestCase;

/**
 * FreightShipResponseShipmentResultsTest Class Doc Comment
 *
 * @category    Class
 * @description ShipmentResults Container.
 * @package     UPS\FreightShipping
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FreightShipResponseShipmentResultsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FreightShipResponseShipmentResults"
     */
    public function testFreightShipResponseShipmentResults()
    {
    }

    /**
     * Test attribute "pickup_request_confirmation_number"
     */
    public function testPropertyPickupRequestConfirmationNumber()
    {
    }

    /**
     * Test attribute "delivery_date"
     */
    public function testPropertyDeliveryDate()
    {
    }

    /**
     * Test attribute "shipment_number"
     */
    public function testPropertyShipmentNumber()
    {
    }

    /**
     * Test attribute "bolid"
     */
    public function testPropertyBolid()
    {
    }

    /**
     * Test attribute "guaranteed_indicator"
     */
    public function testPropertyGuaranteedIndicator()
    {
    }

    /**
     * Test attribute "minimum_charge_applied_indicator"
     */
    public function testPropertyMinimumChargeAppliedIndicator()
    {
    }

    /**
     * Test attribute "rate"
     */
    public function testPropertyRate()
    {
    }

    /**
     * Test attribute "freight_density_rate"
     */
    public function testPropertyFreightDensityRate()
    {
    }

    /**
     * Test attribute "total_shipment_charge"
     */
    public function testPropertyTotalShipmentCharge()
    {
    }

    /**
     * Test attribute "billable_shipment_weight"
     */
    public function testPropertyBillableShipmentWeight()
    {
    }

    /**
     * Test attribute "service"
     */
    public function testPropertyService()
    {
    }

    /**
     * Test attribute "documents"
     */
    public function testPropertyDocuments()
    {
    }

    /**
     * Test attribute "time_in_transit"
     */
    public function testPropertyTimeInTransit()
    {
    }
}
