<?php
/**
 * HandlingUnitCommodityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\FreightShipping
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freight Ship
 *
 * Only users that plan to ship packages manifested, tendered, and delivered by TForce Freight can use the API.
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.45
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\FreightShipping;

use PHPUnit\Framework\TestCase;

/**
 * HandlingUnitCommodityTest Class Doc Comment
 *
 * @category    Class
 * @description Commodity Container.
 * @package     UPS\FreightShipping
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HandlingUnitCommodityTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "HandlingUnitCommodity"
     */
    public function testHandlingUnitCommodity()
    {
    }

    /**
     * Test attribute "number_of_pieces"
     */
    public function testPropertyNumberOfPieces()
    {
    }

    /**
     * Test attribute "packaging_type"
     */
    public function testPropertyPackagingType()
    {
    }

    /**
     * Test attribute "dangerous_goods_indicator"
     */
    public function testPropertyDangerousGoodsIndicator()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "nmfc_commodity_code"
     */
    public function testPropertyNmfcCommodityCode()
    {
    }

    /**
     * Test attribute "freight_class"
     */
    public function testPropertyFreightClass()
    {
    }

    /**
     * Test attribute "dimensions"
     */
    public function testPropertyDimensions()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "commodity_value"
     */
    public function testPropertyCommodityValue()
    {
    }
}
