<?php
/**
 * ShipmentServiceOptionsDeliveryOptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\FreightShipping
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freight Ship
 *
 * Only users that plan to ship packages manifested, tendered, and delivered by TForce Freight can use the API.
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.45
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\FreightShipping;

use PHPUnit\Framework\TestCase;

/**
 * ShipmentServiceOptionsDeliveryOptionsTest Class Doc Comment
 *
 * @category    Class
 * @description DeliveryOptions Container.
 * @package     UPS\FreightShipping
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShipmentServiceOptionsDeliveryOptionsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ShipmentServiceOptionsDeliveryOptions"
     */
    public function testShipmentServiceOptionsDeliveryOptions()
    {
    }

    /**
     * Test attribute "call_before_delivery_indicator"
     */
    public function testPropertyCallBeforeDeliveryIndicator()
    {
    }

    /**
     * Test attribute "holiday_delivery_indicator"
     */
    public function testPropertyHolidayDeliveryIndicator()
    {
    }

    /**
     * Test attribute "inside_delivery_indicator"
     */
    public function testPropertyInsideDeliveryIndicator()
    {
    }

    /**
     * Test attribute "residential_delivery_indicator"
     */
    public function testPropertyResidentialDeliveryIndicator()
    {
    }

    /**
     * Test attribute "weekend_delivery_indicator"
     */
    public function testPropertyWeekendDeliveryIndicator()
    {
    }

    /**
     * Test attribute "lift_gate_required_indicator"
     */
    public function testPropertyLiftGateRequiredIndicator()
    {
    }

    /**
     * Test attribute "limited_access_delivery_indicator"
     */
    public function testPropertyLimitedAccessDeliveryIndicator()
    {
    }
}
