<?php
/**
 * LandedCostRequestQueryRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\LandedCostQuoting
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Landed Cost
 *
 * Landed Cost provides an all-inclusive cost estimate of international shipments.
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.45
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\LandedCostQuoting;

use PHPUnit\Framework\TestCase;

/**
 * LandedCostRequestQueryRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Container for the billing and shipment data. Should be in the first round request of LandedCost. It cannot co-exist with EstimateRequest. If EstimateRequest is not present, this tag must be present.
 * @package     UPS\LandedCostQuoting
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LandedCostRequestQueryRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LandedCostRequestQueryRequest"
     */
    public function testLandedCostRequestQueryRequest()
    {
    }

    /**
     * Test attribute "shipment"
     */
    public function testPropertyShipment()
    {
    }

    /**
     * Test attribute "transaction_reference_id"
     */
    public function testPropertyTransactionReferenceId()
    {
    }

    /**
     * Test attribute "suppress_question_indicator"
     */
    public function testPropertySuppressQuestionIndicator()
    {
    }
}
