<?php
/**
 * CallTagARSCodeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\QuantumView
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Quantum View
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\QuantumView;

use PHPUnit\Framework\TestCase;

/**
 * CallTagARSCodeTest Class Doc Comment
 *
 * @category    Class
 * @description The type of Call Tag service.  Valid values: 00 - No return service 01 - UPS Call Tag Service 02 - UPS Print and Mail 03 - 1 UPS Pickup Attempt 04 - UPS Print Return Label 05 - Online Call Tag (3 UPS Pickup Attempts) 06 - UPS Electronic Return Label 08 - UPS Returns on the Web
 * @package     UPS\QuantumView
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CallTagARSCodeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CallTagARSCode"
     */
    public function testCallTagARSCode()
    {
    }
}
