<?php
/**
 * GenericActivityTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\QuantumView
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Quantum View
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\QuantumView;

use PHPUnit\Framework\TestCase;

/**
 * GenericActivityTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Unique identifier that defines the type of activity.  VM &#x3D; Void for Manifest  UR &#x3D; Undeliverable Returns IR &#x3D; Invoice Removal Successful  TC &#x3D; Transport Company USPS scan PS &#x3D; &#x27;Postal Service Possession Scan&#x27; FN &#x3D; UPS Access Point/Alternate Delivery Location Email Notification Failure DS &#x3D; Destination Scan AG &#x3D; Package is in transit to a UPS facility RE &#x3D; UPS Returns Exchange  RP &#x3D; Retail Pickup UD &#x3D; Updated delivery date                                                                                              OD &#x3D; Out for Delivery                                                                                                        SD &#x3D; Scheduled for Delivery                                                                                              FM &#x3D; Tendered to FMP
 * @package     UPS\QuantumView
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GenericActivityTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GenericActivityType"
     */
    public function testGenericActivityType()
    {
    }
}
