<?php
/**
 * FreightPickupRequestShipmentDetail
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\FreightPickup
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freight Pickup
 *
 * API can be only used by users that plan to ship packages manifested, tendered, and delivered by TForce Freight
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.45
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace UPS\FreightPickup\FreightPickup;

use \ArrayAccess;
use \UPS\FreightPickup\ObjectSerializer;

/**
 * FreightPickupRequestShipmentDetail Class Doc Comment
 *
 * @category Class
 * @description ShipmentDetail Container. Request will contain either ShipmentDetail or ExistingShipmentID container. Not both.
 * @package  UPS\FreightPickup
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FreightPickupRequestShipmentDetail implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'FreightPickupRequest_ShipmentDetail';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'hazmat_indicator' => 'string',
        'packaging_type' => '\UPS\FreightPickup\FreightPickup\ShipmentDetailPackagingType',
        'number_of_pieces' => 'string',
        'description_of_commodity' => 'string',
        'weight' => '\UPS\FreightPickup\FreightPickup\ShipmentDetailWeight'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'hazmat_indicator' => null,
        'packaging_type' => null,
        'number_of_pieces' => null,
        'description_of_commodity' => null,
        'weight' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'hazmat_indicator' => 'HazmatIndicator',
        'packaging_type' => 'PackagingType',
        'number_of_pieces' => 'NumberOfPieces',
        'description_of_commodity' => 'DescriptionOfCommodity',
        'weight' => 'Weight'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'hazmat_indicator' => 'setHazmatIndicator',
        'packaging_type' => 'setPackagingType',
        'number_of_pieces' => 'setNumberOfPieces',
        'description_of_commodity' => 'setDescriptionOfCommodity',
        'weight' => 'setWeight'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'hazmat_indicator' => 'getHazmatIndicator',
        'packaging_type' => 'getPackagingType',
        'number_of_pieces' => 'getNumberOfPieces',
        'description_of_commodity' => 'getDescriptionOfCommodity',
        'weight' => 'getWeight'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['hazmat_indicator'] = isset($data['hazmat_indicator']) ? $data['hazmat_indicator'] : null;
        $this->container['packaging_type'] = isset($data['packaging_type']) ? $data['packaging_type'] : null;
        $this->container['number_of_pieces'] = isset($data['number_of_pieces']) ? $data['number_of_pieces'] : null;
        $this->container['description_of_commodity'] = isset($data['description_of_commodity']) ? $data['description_of_commodity'] : null;
        $this->container['weight'] = isset($data['weight']) ? $data['weight'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['packaging_type'] === null) {
            $invalidProperties[] = "'packaging_type' can't be null";
        }
        if ($this->container['number_of_pieces'] === null) {
            $invalidProperties[] = "'number_of_pieces' can't be null";
        }
        if ($this->container['description_of_commodity'] === null) {
            $invalidProperties[] = "'description_of_commodity' can't be null";
        }
        if ($this->container['weight'] === null) {
            $invalidProperties[] = "'weight' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets hazmat_indicator
     *
     * @return string
     */
    public function getHazmatIndicator()
    {
        return $this->container['hazmat_indicator'];
    }

    /**
     * Sets hazmat_indicator
     *
     * @param string $hazmat_indicator The presence of the tag HazmatIndicator indicates that the commodity is of type dangerous goods. Required if one or more commodities within the shipment is hazardous.
     *
     * @return $this
     */
    public function setHazmatIndicator($hazmat_indicator)
    {
        $this->container['hazmat_indicator'] = $hazmat_indicator;

        return $this;
    }

    /**
     * Gets packaging_type
     *
     * @return \UPS\FreightPickup\FreightPickup\ShipmentDetailPackagingType
     */
    public function getPackagingType()
    {
        return $this->container['packaging_type'];
    }

    /**
     * Sets packaging_type
     *
     * @param \UPS\FreightPickup\FreightPickup\ShipmentDetailPackagingType $packaging_type packaging_type
     *
     * @return $this
     */
    public function setPackagingType($packaging_type)
    {
        $this->container['packaging_type'] = $packaging_type;

        return $this;
    }

    /**
     * Gets number_of_pieces
     *
     * @return string
     */
    public function getNumberOfPieces()
    {
        return $this->container['number_of_pieces'];
    }

    /**
     * Sets number_of_pieces
     *
     * @param string $number_of_pieces Number of pieces.
     *
     * @return $this
     */
    public function setNumberOfPieces($number_of_pieces)
    {
        $this->container['number_of_pieces'] = $number_of_pieces;

        return $this;
    }

    /**
     * Gets description_of_commodity
     *
     * @return string
     */
    public function getDescriptionOfCommodity()
    {
        return $this->container['description_of_commodity'];
    }

    /**
     * Sets description_of_commodity
     *
     * @param string $description_of_commodity Description of the line item.
     *
     * @return $this
     */
    public function setDescriptionOfCommodity($description_of_commodity)
    {
        $this->container['description_of_commodity'] = $description_of_commodity;

        return $this;
    }

    /**
     * Gets weight
     *
     * @return \UPS\FreightPickup\FreightPickup\ShipmentDetailWeight
     */
    public function getWeight()
    {
        return $this->container['weight'];
    }

    /**
     * Sets weight
     *
     * @param \UPS\FreightPickup\FreightPickup\ShipmentDetailWeight $weight weight
     *
     * @return $this
     */
    public function setWeight($weight)
    {
        $this->container['weight'] = $weight;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
