<?php
/**
 * PendingStatusPickupStatusMessageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\Pickup
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Pickup
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\Pickup;

use PHPUnit\Framework\TestCase;

/**
 * PendingStatusPickupStatusMessageTest Class Doc Comment
 *
 * @category    Class
 * @description The status for on-callpickup. PickupPendingStatusResponse will only display incomplete status for today and tomorrow only.  002 and 012 are the most common responses. 001 &#x3D; Received at dispatch 002 &#x3D; Dispatched to driver 003 &#x3D; Order successfully completed 004 &#x3D; Order unsuccessfully completed 005 &#x3D; Missed commit � Updated ETA supplied by driver 007 &#x3D; Cancelled 008 &#x3D; Order has invalid order status 012 &#x3D; Your pickup request is being processed
 * @package     UPS\Pickup
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PendingStatusPickupStatusMessageTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PendingStatusPickupStatusMessage"
     */
    public function testPendingStatusPickupStatusMessage()
    {
    }
}
