<?php
/**
 * PickupDateInfoCloseTimeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\Pickup
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Pickup
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\Pickup;

use PHPUnit\Framework\TestCase;

/**
 * PickupDateInfoCloseTimeTest Class Doc Comment
 *
 * @category    Class
 * @description Pickup location&#x27;s local close time. - User provided Close Time must be later than the Earliest Allowed Customer Close Time.  - Earliest Allowed Customer Close Time is defined by UPS pickup operation system.  - CloseTime minus ReadyTime must be greater than the LeadTime.  - LeadTime is determined by UPS pickup operation system. LeadTime is the minimum amount of time UPS requires between customer�s request for a pickup and driver arriving at the location for the pickup.  Format: HHmm Hour: 0-23 Minute: 0-59
 * @package     UPS\Pickup
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PickupDateInfoCloseTimeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PickupDateInfoCloseTime"
     */
    public function testPickupDateInfoCloseTime()
    {
    }
}
