<?php
/**
 * PickupCreationRequestPaymentMethodTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\Pickup
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Pickup
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\Pickup;

use PHPUnit\Framework\TestCase;

/**
 * PickupCreationRequestPaymentMethodTest Class Doc Comment
 *
 * @category    Class
 * @description The payment method to pay for this on call pickup. 00 &#x3D; No payment needed 01 &#x3D; Pay by shipper account 03 &#x3D; Pay by charge card 04 &#x3D; Pay by 1Z tracking number 05 &#x3D; Pay by check or money order 06 &#x3D; Cash(applicable only for these countries - BE,FR,DE,IT,MX,NL,PL,ES,GB,CZ,HU,FI,NO) 07&#x3D;Pay by PayPal Refer to Appendix # for valid payment methods for CZ, HU, FI and NO   For countries and (or) zip codes where pickup is free of charge, please submit 00, means no payment needed as payment method.  - If 01 is the payment method, then ShipperAccountNumber and ShipperAccount CountryCode must be provided. - If 03 is selected, then CreditCard information should be provided. - If 04 is selected, then the shipper agreed to pay for the pickup packages. - If 05 is selected, then the shipper will pay for the pickup packages with a check or money order.
 * @package     UPS\Pickup
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PickupCreationRequestPaymentMethodTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PickupCreationRequestPaymentMethod"
     */
    public function testPickupCreationRequestPaymentMethod()
    {
    }
}
