<?php
/**
 * PickupGetServiceCenterFacilitiesRequestOriginAddressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\Pickup
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Pickup
 *
 * Using the Pickup API, applications can schedule pickups, manage previously scheduled pickups, or cancel previously scheduled pickups.
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.45
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\Pickup;

use PHPUnit\Framework\TestCase;

/**
 * PickupGetServiceCenterFacilitiesRequestOriginAddressTest Class Doc Comment
 *
 * @category    Class
 * @description Indicates the address of the shipper to allow for the nearest Drop off facility Search.  Conditionally required for drop off location search.
 * @package     UPS\Pickup
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PickupGetServiceCenterFacilitiesRequestOriginAddressTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PickupGetServiceCenterFacilitiesRequestOriginAddress"
     */
    public function testPickupGetServiceCenterFacilitiesRequestOriginAddress()
    {
    }

    /**
     * Test attribute "street_address"
     */
    public function testPropertyStreetAddress()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "state_province"
     */
    public function testPropertyStateProvince()
    {
    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {
    }

    /**
     * Test attribute "origin_search_criteria"
     */
    public function testPropertyOriginSearchCriteria()
    {
    }
}
