<?php
/**
 * EMailNotificationEventTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\TForceFreightShipping
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freight Ship
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\TForceFreightShipping;

use PHPUnit\Framework\TestCase;

/**
 * EMailNotificationEventTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Type of event for POM Notification. Add up to four events. 01 &#x3D; PICKUP_REQUEST_CONFIRM 02 &#x3D; DRIVER_EN_ROUTE 03 &#x3D; PICKUP_SECURED 04 &#x3D; PICKUP_EXCEPTION
 * @package     UPS\TForceFreightShipping
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EMailNotificationEventTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EMailNotificationEventType"
     */
    public function testEMailNotificationEventType()
    {
    }
}
