<?php
/**
 * PickupOptionsLimitedAccessPickupIndicatorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\TForceFreightShipping
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freight Ship
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\TForceFreightShipping;

use PHPUnit\Framework\TestCase;

/**
 * PickupOptionsLimitedAccessPickupIndicatorTest Class Doc Comment
 *
 * @category    Class
 * @description The presence of the tag LimitedAccessPickupIndicator indicates that there is limited access for pickups.
 * @package     UPS\TForceFreightShipping
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PickupOptionsLimitedAccessPickupIndicatorTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PickupOptionsLimitedAccessPickupIndicator"
     */
    public function testPickupOptionsLimitedAccessPickupIndicator()
    {
    }
}
