<?php
/**
 * ShipmentShipmentServiceOptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\TForceFreightShipping
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Freight Ship
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\TForceFreightShipping;

use PHPUnit\Framework\TestCase;

/**
 * ShipmentShipmentServiceOptionsTest Class Doc Comment
 *
 * @category    Class
 * @description ShipmentServiceOptions Container.
 * @package     UPS\TForceFreightShipping
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShipmentShipmentServiceOptionsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ShipmentShipmentServiceOptions"
     */
    public function testShipmentShipmentServiceOptions()
    {
    }

    /**
     * Test attribute "e_mail_information"
     */
    public function testPropertyEMailInformation()
    {
    }

    /**
     * Test attribute "pickup_options"
     */
    public function testPropertyPickupOptions()
    {
    }

    /**
     * Test attribute "delivery_options"
     */
    public function testPropertyDeliveryOptions()
    {
    }

    /**
     * Test attribute "over_seas_leg"
     */
    public function testPropertyOverSeasLeg()
    {
    }

    /**
     * Test attribute "cod"
     */
    public function testPropertyCod()
    {
    }

    /**
     * Test attribute "dangerous_goods"
     */
    public function testPropertyDangerousGoods()
    {
    }

    /**
     * Test attribute "sorting_and_segregating"
     */
    public function testPropertySortingAndSegregating()
    {
    }

    /**
     * Test attribute "declared_value"
     */
    public function testPropertyDeclaredValue()
    {
    }

    /**
     * Test attribute "excess_declared_value"
     */
    public function testPropertyExcessDeclaredValue()
    {
    }

    /**
     * Test attribute "handling_charge"
     */
    public function testPropertyHandlingCharge()
    {
    }

    /**
     * Test attribute "freezable_protection_indicator"
     */
    public function testPropertyFreezableProtectionIndicator()
    {
    }

    /**
     * Test attribute "extreme_length_indicator"
     */
    public function testPropertyExtremeLengthIndicator()
    {
    }

    /**
     * Test attribute "linear_feet"
     */
    public function testPropertyLinearFeet()
    {
    }
}
