<?php
/**
 * ChemicalRecordProperShippingNameTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  UPS\DangerousGoods
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Dangerous Goods Utility
 *
 * The Dangerous Goods API provides the ability to determine what Dangerous Goods (also known as Hazardous Materials) can be carried by UPS.
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.45
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace UPS\DangerousGoods;

use PHPUnit\Framework\TestCase;

/**
 * ChemicalRecordProperShippingNameTest Class Doc Comment
 *
 * @category    Class
 * @description The Proper Shipping Name assigned by ADR, CFR or IATA.   Required if CommodityRegulatedLevelCode &#x3D; LR, LQ or FR.
 * @package     UPS\DangerousGoods
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChemicalRecordProperShippingNameTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ChemicalRecordProperShippingName"
     */
    public function testChemicalRecordProperShippingName()
    {
    }
}
